/*
The following code defines tables on BigQuery for each given source. 
Note: Due to time constrains on this project, only the first table QA_PROJECT.QA.CONVERSATIONS has their descriptions written in. The other tables will use a sample text to describe them
*/

CREATE TABLE
  `QA_PROJECT.QA.CONVERSATIONS` ( unique_id STRING OPTIONS(description="Unique identifier of the table. Combination of payment_token_id and external_ticket_id."),
    payment_id INT64 OPTIONS(description="Unique identifier of the payment"),
    payment_token_id INT64 OPTIONS(description="Unique identifier of the payment token"),
    external_ticket_id INT64 OPTIONS(description="Conversation ticket identifier"),
    conversation_created_at TIMESTAMP OPTIONS(description="Timestamp when the conversation with the customer was created"),
    conversation_created_at_date DATE OPTIONS(description="Date when the conversation with the customer was created"),
    channel STRING OPTIONS(description="Channel through which the conversation took place (e.g.  chat, email, conversation, web)"),
    assignee_id INT64 OPTIONS(description="Unique identifier of the agent who was assigned to the ticket"),
    updated_at TIMESTAMP OPTIONS(description="Timestamp when the last conversation update took place"),
    closed_at TIMESTAMP OPTIONS(description="Timestamp when the conversation was closed at"),
    message_count INT64 OPTIONS(description="Number of messages exchanged between Agent and Customer"),
    last_reply_at TIMESTAMP OPTIONS(description="Timestamp when the last reply was given in the conversation"),
    LANGUAGE STRING OPTIONS(description="Language in which the conversation took place"),
    imported_at TIMESTAMP OPTIONS(description="Timestamp when the conversation was last imported at"),
    unique_public_agent_count INT64 OPTIONS(description="Number of Agents involved in the conversation "),
    public_mean_character_count FLOAT64 OPTIONS(description="Mean number of characters sent between all public messages"),
    public_mean_word_count FLOAT64 OPTIONS(description="Mean number of words sent between all public messages"),
    private_message_count INT64 OPTIONS(description="Number of internal messages per conversation"),
    public_message_count INT64 OPTIONS(description="Number of public messages per conversation"),
    klaus_sentiment STRING OPTIONS(description="Assigned sentiment generated by Klaus' AI"),
    is_closed BOOL OPTIONS(description="Flag to identify if the conversation has been marked as closed"),
    agent_most_public_messages INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun"),
    first_response_time INT64 OPTIONS(description="Seconds incurred since the start of the conversation until the first response given by the Agent"),
    first_resolution_time_seconds INT64 OPTIONS(description="Seconds incurred since the start of the conversation until the first resolution given by the Agent"),
    full_resolution_time_seconds INT64 OPTIONS(description="Seconds incurred since the start of the conversation until the last resolution given by the Agent"),
    most_active_internal_user_id INT64 OPTIONS(description="User ID of the most active Agent within the conversation"),
    deleted_at STRING OPTIONS(description="Timestamp when the conversation was deleted at") ) 
    OPTIONS( description="Table contains information on conversations for each Merchant Support Ticket ID. There is information about: timestamps, word/character counts, sentiment of the conversation, user_ids, etc" );



CREATE TABLE
  `QA_PROJECT.QA.MANUAL_REVIEWS` ( review_id INT64 OPTIONS(description="Unique identifier of the table"),
    payment_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    payment_token_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    created TIMESTAMP OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    conversation_created_at TIMESTAMP OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    conversation_created_date DATE OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    conversation_external_id FLOAT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    team_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    reviewer_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    reviewee_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    comment_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    scorecard_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    scorecard_tag STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    score FLOAT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    updated_at TIMESTAMP OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    updated_by INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    assignment_review BOOL OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    seen BOOL OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    disputed BOOL OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    review_time_seconds STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    assignment_name STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    imported_at TIMESTAMP OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut") ) 
    OPTIONS( description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut" );



CREATE TABLE
  `QA_PROJECT.QA.MANUAL_RATINGS` ( unique_id STRING OPTIONS(description="Unique identifier of the table. Combination of review_id and category_id."),
    payment_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    team_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    review_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    category_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    rating INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    cause STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    rating_max INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    weight FLOAT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    critical BOOL OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    category_name STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut") ) 
    OPTIONS( description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut" );



CREATE TABLE
  `QA_PROJECT.QA.AUTOQA_REVIEWS` ( autoqa_review_id STRING OPTIONS(description="Unique identifier of the table"),
    payment_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    payment_token_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    external_ticket_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    created_at TIMESTAMP OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    conversation_created_at TIMESTAMP OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    conversation_created_date DATE OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    team_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    reviewee_internal_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    updated_at TIMESTAMP OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut") ) 
    OPTIONS( description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut" );



CREATE TABLE
  `QA_PROJECT.QA.AUTOQA_RATINGS` ( autoqa_review_id STRING OPTIONS(description="Unique identifier of the table"),
    autoqa_rating_id STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    payment_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    team_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    payment_token_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    external_ticket_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    rating_category_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    rating_category_name STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    rating_scale_score INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    score INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    reviewee_internal_id INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut") ) 
    OPTIONS( description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut" );



CREATE TABLE
  `QA_PROJECT.QA.AUTOQA_ROOT_CAUSE` ( unique_id STRING OPTIONS(description="Unique identifier of the table"),
    autoqa_rating_id STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    category STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    count INT64 OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut"),
    root_cause STRING OPTIONS(description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut")) 
    OPTIONS( description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut" );


